/* =====================================================================
   CASE STUDY 1: RETAIL ANALYTICS
   Tables: fact, Product, Location
   Platform: Microsoft SQL Server (SSMS)
   ===================================================================== */

CREATE DATABASE sqlcasestudy1;
GO
USE sqlcasestudy1;
GO


-- 1. Display the number of states present in the LocationTable.
SELECT COUNT(DISTINCT State) AS num_states
FROM Location;


-- 2. How many products are of Regular type?
SELECT COUNT(*) AS regular_count
FROM Product
WHERE Type = 'Regular';


-- 3. How much spending has been done on marketing of Product ID 1?
SELECT SUM(Marketing) AS spending
FROM fact
WHERE ProductId = 1;


-- 4. What is the minimum sales of a product?
SELECT MIN(Sales) AS min_sales
FROM fact;


-- 5. Display the max Cost of Goods Sold (COGS).
-- FIX: original used "ORDER BY sales DESC" which returns COGS of the
-- highest-SALES row, not the actual maximum COGS. MAX(COGS) is correct.
SELECT MAX(COGS) AS max_COGS
FROM fact;


-- 6. Display the details of the product where Product Type is Coffee.
SELECT * FROM Product
WHERE Product_Type = 'Coffee';


-- 7. Display the details where Total Expenses are greater than 40.
SELECT * FROM fact
WHERE Total_Expenses > 40;


-- 8. What is the average sales in Area Code 719?
SELECT AVG(Sales) AS avg_sales
FROM fact
WHERE Area_Code = 719;


-- 9. Find out the total profit generated by Colorado state.
SELECT SUM(f.Profit) AS total_profit
FROM fact AS f
INNER JOIN Location AS l ON f.Area_Code = l.Area_Code
WHERE l.State = 'Colorado';


-- 10. Display the average inventory for each Product ID.
SELECT ProductId, AVG(Inventory) AS Avg_Inventory
FROM fact
GROUP BY ProductId
ORDER BY ProductId;


-- 11. Display states in sequential (alphabetical) order from the Location Table.
SELECT DISTINCT State
FROM Location
ORDER BY State;


-- 12. Display the average budget of products where average budget margin > 100.
SELECT ProductId, AVG(Budget_Sales) AS avg_budget
FROM fact
GROUP BY ProductId
HAVING AVG(Budget_Margin) > 100;


-- 13. What is the total sales done on date 2010-01-01?
SELECT SUM(Sales) AS total_sales
FROM fact
WHERE Date = '1/1/2010';


-- 14. Display the average total expense of each Product ID on an individual date.
SELECT Date, ProductId, AVG(Total_Expenses) AS avg_total_expense
FROM fact
GROUP BY Date, ProductID;


-- 15. Display: date, productID, product_type, product, sales, profit, state, area_code.
SELECT
    f.Date,
    f.ProductId,
    p.Product_Type,
    p.Product,
    f.Sales,
    f.Profit,
    l.State,
    f.Area_Code
FROM fact f
JOIN Product p ON f.ProductID = p.ProductID
JOIN Location l ON f.Area_Code = l.Area_Code;


-- 16. Display the rank without any gap to show the sales-wise rank (DENSE_RANK).
SELECT Date, ProductId, Sales, DENSE_RANK() OVER (ORDER BY Sales DESC) AS sales_rank
FROM fact;


-- 17. Find the state-wise profit and sales.
SELECT l.State, SUM(f.Profit) AS total_profit, SUM(f.Sales) AS total_sales
FROM fact f
JOIN Location l ON f.Area_Code = l.Area_Code
GROUP BY l.State;


-- 18. Find the state-wise profit and sales along with the product name.
SELECT l.State, p.Product, SUM(f.Profit) AS total_profit, SUM(f.Sales) AS total_sales
FROM fact AS f
JOIN Location AS l ON f.Area_Code = l.Area_Code
JOIN Product p ON f.ProductId = p.ProductId
GROUP BY l.State, p.Product;


-- 19. If there is an increase in sales of 5%, calculate the increased sales.
SELECT Date, ProductId, Sales, Sales * 1.05 AS increased_sales
FROM fact;


-- 20. Find the maximum profit along with the Product ID and Product Type.
SELECT f.ProductId, p.Product_Type, MAX(f.Profit) AS max_profit
FROM fact AS f
JOIN Product AS p ON f.ProductId = p.ProductId
GROUP BY f.ProductId, p.Product_Type
ORDER BY max_profit DESC;


-- 21. Create a stored procedure to fetch results by product type from Product Table.
CREATE OR ALTER PROCEDURE GetProductByType
    @p_type VARCHAR(50)
AS
BEGIN
    SELECT *
    FROM Product
    WHERE Product_Type = @p_type;
END;
GO

-- Call the stored procedure:
EXEC GetProductByType @p_type = 'Coffee';


-- 22. If Total Expenses < 60 then label as 'Profit', else 'Loss'.
SELECT *,
    CASE
        WHEN Total_Expenses < 60 THEN 'Profit'
        ELSE 'Loss'
    END AS status
FROM fact;


-- 23. Total weekly sales with date and product ID — use ROLLUP for hierarchical order.
SELECT
    CONCAT(DATEPART(YEAR, Date), RIGHT('0' + CAST(DATEPART(ISO_WEEK, Date) AS VARCHAR(2)), 2)) AS year_week,
    ProductId,
    SUM(Sales) AS weekly_sales
FROM fact
GROUP BY ROLLUP (
    CONCAT(DATEPART(YEAR, Date), RIGHT('0' + CAST(DATEPART(ISO_WEEK, Date) AS VARCHAR(2)), 2)),
    ProductId
);


-- 24. Apply UNION and INTERSECT on tables containing Area Code attribute.

-- UNION: all distinct area codes from both tables
SELECT Area_Code FROM fact
UNION
SELECT Area_Code FROM Location
ORDER BY Area_Code;

-- INTERSECT: area codes common to both tables
-- FIX: original only had UNION; INTERSECT was missing.
SELECT Area_Code FROM fact
INTERSECT
SELECT Area_Code FROM Location
ORDER BY Area_Code;


-- 25. Create a user-defined function to fetch a particular product type from Product Table.
CREATE OR ALTER FUNCTION GetProductsByType
(
    @p_type VARCHAR(50) -- Input parameter
)
RETURNS TABLE
AS
RETURN
(
    SELECT ProductId, Product_Type, Product, Type
    FROM Product
    WHERE Product_Type = @p_type
);
GO

-- Call the function:
SELECT * FROM GetProductsByType('Coffee');


-- 26. Change Product Type from Coffee to Tea where Product ID = 1, then undo it.
BEGIN TRANSACTION;

UPDATE Product
SET Product_Type = 'Tea'
WHERE ProductId = 1;

SELECT * FROM Product WHERE ProductID = 1;

ROLLBACK TRANSACTION;

SELECT * FROM Product WHERE ProductId = 1; -- confirms reverted to 'Coffee'


-- 27. Display date, Product ID and sales where Total Expenses are between 100 and 200.
SELECT Date, ProductId, Sales
FROM fact
WHERE Total_Expenses BETWEEN 100 AND 200;


-- 28. Delete the records in the Product Table for Regular type.
BEGIN TRANSACTION;

DELETE FROM Product
WHERE Type = 'Regular';

SELECT COUNT(*) FROM Product;

COMMIT TRANSACTION;


-- 29. Display the ASCII value of the fifth character from the column Product.
SELECT Product, ASCII(SUBSTRING(Product, 5, 1)) AS ascii_5th_char
FROM Product;
